<?php

/**
 * Test class for WirecardCEE_QMore_Response_Backend_Order_Payment_Ideal
 * Generated by PHPUnit on 2011-06-24 at 13:26:16.
 */
class WirecardCEE_QMore_Response_Backend_Order_Payment_IdealTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var WirecardCEE_QMore_Response_Backend_GetOrderDetails
     */
    protected $object;
    protected $_secret = 'B8AKTPWBRMNBV455FG6M2DANE99WU2';
    protected $_customerId = 'D200001';
    protected $_shopId = 'qmore';
    protected $_language = 'en';
    protected $_toolkitPassword = 'jcv45z';
    protected $_orderNumber = 1767634;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $oBackClient = new WirecardCEE_QMore_BackendClient(Array(
            'CUSTOMER_ID' => $this->_customerId,
            'SHOP_ID'     => $this->_shopId,
            'SECRET'      => $this->_secret,
            'LANGUAGE'    => $this->_language,
            'PASSWORD'    => $this->_toolkitPassword
        ));

        $this->object = $oBackClient->getOrderDetails($this->_orderNumber)->getOrder()->getPayments()->current();
    }

    public function testGetConsumerName()
    {
        $this->assertEquals('Test Consumer', $this->object->getConsumerName());
    }

    public function testGetConsumerCity()
    {
        $this->assertEquals('Den Haag', $this->object->getConsumerCity());
    }

    public function testGetConsumerAccountNumber()
    {
        $this->assertEquals('P001234567', $this->object->getConsumerAccountNumber());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object = null;
        unset( $this );
    }
}
