<?php

/**
 * Test class for WirecardCEE_Client_QMore_Return_Cancel.
 * Generated by PHPUnit on 2011-06-24 at 13:25:58.
 */
class WirecardCEE_QMore_Return_CancelTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var WirecardCEE_QMore_Return_Cancel
     */
    protected $object;
    protected $_returnData = Array('paymentState' => 'CANCEL');

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new WirecardCEE_QMore_Return_Cancel($this->_returnData);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testPaymentState()
    {
        $this->assertEquals('CANCEL', $this->object->getPaymentState());
    }

    public function testValidate()
    {
        $this->assertTrue($this->object->validate());
    }

    public function testGetReturned()
    {
        $this->assertEquals($this->_returnData, $this->object->getReturned());
    }
}

?>
