<?php

/**
 * Test class for WirecardCEE_Client_QPay_Response_Toolkit_Order_Payment_Sofortueberweisung.
 * Generated by PHPUnit on 2011-06-24 at 13:26:16.
 */
class WirecardCEE_QPay_Response_Toolkit_Order_Payment_SofortueberweisungTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var WirecardCEE_QPay_Response_Toolkit_Order_Payment_Sofortueberweisung
     */
    protected $object;
    protected $_secret = 'B8AKTPWBRMNBV455FG6M2DANE99WU2';
    protected $_customerId = 'D200001';
    protected $_shopId = '';
    protected $_language = 'en';
    protected $_toolkitPassword = 'jcv45z';
    protected $_orderNumber = 543132154;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $customerId      = $this->_customerId;
        $shopId          = $this->_shopId;
        $secret          = $this->_secret;
        $language        = $this->_language;
        $toolkitPassword = $this->_toolkitPassword;

        $oToolkitClient = new WirecardCEE_QPay_ToolkitClient(Array(
            'CUSTOMER_ID'      => $customerId,
            'SHOP_ID'          => $shopId,
            'SECRET'           => $secret,
            'LANGUAGE'         => $language,
            'TOOLKIT_PASSWORD' => $toolkitPassword
        ));

        $this->object = $oToolkitClient->getOrderDetails($this->_orderNumber)->getOrder()->getPayments()->current();
    }

    public function testGetSenderAccountOwner()
    {
        $this->assertEquals('Test Consumer', $this->object->getSenderAccountOwner());
    }

    public function testGetSenderAccountNumber()
    {
        $this->assertEquals('1234567890', $this->object->getSenderAccountNumber());
    }

    public function testGetSenderBankNumber()
    {
        $this->assertEquals('1234578', $this->object->getSenderBankNumber());
    }

    public function testGetSenderBankName()
    {
        $this->assertEquals('Test Bank', $this->object->getSenderBankName());
    }

    public function testGetSenderBic()
    {
        $this->assertEquals('PNAGDE00000', $this->object->getSenderBic());
    }

    public function testGetSenderIban()
    {
        $this->assertEquals('DE0000000000000000', $this->object->getSenderIban());
    }

    public function testGetSenderCountry()
    {
        $this->assertEquals('DE', $this->object->getSenderCountry());
    }

    public function testGetSecurityCriteria()
    {
        $this->assertEquals('1', $this->object->getSecurityCriteria());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object = null;
        unset( $this );
    }
}
