<?php

/**
 * Test class for WirecardCEE_QMore_Response_InitiationTest.
 * Generated by PHPUnit on 2011-06-24 at 13:26:02.
 */
class WirecardCEE_QMore_Response_InitiationTest extends PHPUnit_Framework_TestCase
{

    /**
     *
     * @var WirecardCEE_QMOre_Response_Initiation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $zendHttpResponse = new \GuzzleHttp\Psr7\Response(200, Array(),
            'pre=bla&redirectUrl=http://www.example.com&su=blub');
        $this->object     = new WirecardCEE_QMore_Response_Initiation($zendHttpResponse);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        unset( $this );
    }

    public function testGetStatus()
    {
        $this->assertEquals(WirecardCEE_QMore_Response_Initiation::STATE_SUCCESS, $this->object->getStatus());
    }

    public function testGetRedirectUrl()
    {
        $this->assertEquals('http://www.example.com', $this->object->getRedirectUrl());
    }

    public function testGetStatusFailed()
    {
        $this->object = $this->_fail200Response();
        $this->assertEquals(WirecardCEE_QMore_Response_Initiation::STATE_FAILURE, $this->object->getStatus());
    }

    protected function _fail200Response()
    {
        $zendHttpResponse = new \GuzzleHttp\Psr7\Response(200, Array(), 'pre=bla&su=blub');

        return new WirecardCEE_QMore_Response_Initiation($zendHttpResponse);
    }
}


