<?php

/**
 * Test class for WirecardCEE_QMore_DataStorage_Response_Initiation.
 * Generated by PHPUnit on 2011-12-30 at 09:22:50.
 */
class WirecardCEE_QMore_DataStorage_Response_InitiationTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var WirecardCEE_QMore_DataStorage_Response_Initiation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $httpResponse = new \GuzzleHttp\Psr7\Response(200, Array(),
            'pre=bla&storageId=testStorageId&su=blub&javascriptUrl=http://www.example.com');
        $this->object = new WirecardCEE_QMore_DataStorage_Response_Initiation($httpResponse);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testGetStatus()
    {
        $this->assertEquals(WirecardCEE_QMore_DataStorage_Response_Initiation::STATE_SUCCESS,
            $this->object->getStatus());
    }

    public function testGetErrors()
    {
        $this->assertEquals(Array(), $this->object->getErrors());
    }

    public function testGetStorageId()
    {
        $this->assertEquals('testStorageId', $this->object->getStorageId());
    }

    public function testJavascriptUrl()
    {
        $this->assertEquals('http://www.example.com', $this->object->getJavascriptUrl());
    }

    public function testFailureGetStatus()
    {
        $this->_200ErrorResponse();
        $this->assertEquals(WirecardCEE_QMore_DataStorage_Response_Initiation::STATE_FAILURE,
            $this->object->getStatus());
    }

    public function testFailureGetErrors()
    {
        $this->_200ErrorResponse();
        $this->assertInternalType(PHPUnit_Framework_Constraint_IsType::TYPE_ARRAY, $this->object->getErrors());
        foreach ($this->object->getErrors() as $error) {
            $this->assertInstanceOf('WirecardCEE_Stdlib_Error', $error);
        }
        $this->assertEquals($this->object->getNumberOfErrors(), count($this->object->getErrors()));
    }

    protected function _200ErrorResponse()
    {
        $httpResponse = new \GuzzleHttp\Psr7\Response(200, Array(),
            'pre=bla&error.1.errorCode=12345&error.1.message=testMessage&error.2.errorCode=54321&error.2.message=testMessage2&errors=2&su=blub');
        $this->object = new WirecardCEE_QMore_DataStorage_Response_Initiation($httpResponse);
    }
}

?>
